title: "Trading AI Blog"
description: "AI-generated articles about algorithmic trading and investing"
theme: minima
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /:name/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
